# Generated by Django 4.2.17 on 2025-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='sugar_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount of sugar consumed (grams) during this exercise session', max_digits=6, null=True),
        ),
    ]
