# Generated by Django 4.2.17 on 2025-08-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_entry_sugar_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='sugar_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount of sugar consumed (grams) during this exercise session', max_digits=6, null=True),
        ),
    ]
