# Generated by Django 4.2.17 on 2025-08-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_snack'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='serving_size',
            field=models.CharField(blank=True, help_text='Serving size (optional)', max_length=50),
        ),
    ]
