# Generated by Django 4.2.17 on 2025-08-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_snack_serving_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='sugar_grams',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='sugar_content',
        ),
        migrations.AddField(
            model_name='entry',
            name='carbohydrate_grams',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Amount of Carbohydrates consumed (grams) during this exercise session', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='carbohydrate_grams',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Carbohydrate content in grams', max_digits=6),
        ),
    ]
